version: "3"
services:
  monnitor:
    image: mongodb_agent:latest
    container_name: mongodb_agent
    volumes:
      - ./conf/mongomon.conf:/mongomon/conf/mongomon.conf
      # - ./bin/:/mongomon/bin
    restart: always
    network_mode: "host"
    depends_on:
      - dns_proxy
  dns_proxy:
    image: defreitas/dns-proxy-server
    container_name: dns_proxy
    volumes:
      - /opt/dns-proxy-server/conf:/app/conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    ports:
      - 5380:5380
    network_mode: "host"

